CREATE TABLE CINEAPP_FILMES

(COD_FILME 	 NUMBER(15)    NOT NULL,
 COD_DIRETOR NUMBER(15)    NOT NULL, 
 NOME        VARCHAR2(150) NOT NULL,
 DESCRICAO   VARCHAR2(250) NOT NULL,
 GENERO      VARCHAR2(25),
 PRIMARY KEY (COD_FILME),
 FOREIGN KEY (COD_DIRETOR) REFERENCES CINEAPP_DIRETOR(COD_DIRETOR));

COMMIT;
